TLP_ENABLE=1
TLP_WARN_LEVEL=2
TLP_DEFAULT_MODE=BAT
TLP_PERSISTENT_DEFAULT=1
SOUND_POWER_SAVE_ON_BAT=1
SOUND_POWER_SAVE_CONTROLLER=Y
RESTORE_THRESHOLDS_ON_BAT=1
TPSMAPI_ENABLE=1
BAY_POWEROFF_ON_BAT=1
DISK_SPINDOWN_TIMEOUT_ON_BAT="1 1"
