[Service]
ExecStart=
ExecStart=rpm-ostree upgrade -q --peer --bypass-driver --allow-downgrade --trigger-automatic-update-policy
Nice=19
IOSchedulingClass=best-effort
IOSchedulingPriority=7
RestartSec=1s
RestrictRealtime=true
