[Resolve]
#Adblocking is required to be a part of this list
DNS=2a01:4f8:1c0c:8274::1#noads.libredns.gr
DNS=2407:3640:2205:1668::1#dot-sg.blahdns.com
DNS=2a01:4f8:c17:ec67::1#dot-de.blahdns.com
DNS=2620:fe::11#dns11.quad9.net 2620:fe::fe:11#dns11.quad9.net
DNS=2a10:50c0::ad1:ff#dns.adguard.com 2a10:50c0::ad2:ff#dns.adguard.com
DNS=2606:1a40:1::2#p2.freedns.controld.com 2606:1a40::2#p2.freedns.controld.com
DNS=2a07:e340::4#base.dns.mullvad.net
DNSSEC=no
DNSOverTLS=yes
Cache=yes
Domains=~.
