[Resolve]
# Non-Profit and Ad/Malware/Filter Blocking preferred

DNS=noads.libredns.gr
DNS=dot-sg.blahdns.com
DNS=dot-de.blahdns.com
DNS=dns11.quad9.net
DNS=dns.adguard.com
DNS=p2.freedns.controld.com
DNS=base.dns.mullvad.net
DNS=dns.decloudus.com
DNSSEC=no
DNSOverTLS=yes
Domains=~.
