[main]
allow_downgrade=False #
allow_vendor_change=True #
assumeno=False #
assumeyes=True #
autocheck_running_kernel=True #
best=False #
build_cache=True #
cacheonly=False #
check_config_file_age=True #
clean_requirements_on_remove=True #
countme=1 #
debug_solver=False #
debuglevel=0 #
defaultyes=True #
deltarpm=False
deltarpm_percentage=0
diskspacecheck=True #
enablegroups=True #
exclude_from_weak_autodetect=True
fastestmirror=True #
gpgkey_dns_verification=True #
ignorearch=True #
install_weak_deps=False #
keepcache=False #
log_compress=True #
log_rotate=6 #
logfilelevel=0 #
max_parallel_downloads=20 #
metadata_expire=3h #
minrate=1 #
module_obsoletes=True #
retries=32 #
module_stream_switch=True
multilib_policy="best"
obsoletes=True #
plugins=True #
protect_running_kernel=True #
skip_if_unavailable=True #
strict=False #
throttle=0 #
timeout=60
upgrade_group_objects_upgrade=True #
zchunk=True #
