[main]
allow_downgrade=True
allow_vendor_change=True
best=False
cacheonly=False
check_config_file_age=True
clean_requirements_on_remove=True
debug_solver=True
defaultyes=True
exclude_from_weak_autodetect=True
ignorearch=False
install_weak_deps=True
keepcache=False
module_stream_switch=True
plugins=True
protect_running_kernel=True
skip_broken=True
skip_unavailable=True
zchunk=True
bandwidth=0
build_cache=True
countme=1
deltarpm=False
deltarpm_percentage=0
enablegroups=True
fastestmirror=True
max_parallel_downloads=20
metadata_expire=1h
minrate=1
skip_if_unavailable=False
throttle=0
timeout=60
