[main]
allow_downgrade=True #
allow_vendor_change=True #
assumeno=False #
assumeyes=True #
autocheck_running_kernel=True #
best=False #
build_cache=True #
cacheonly=False #
check_config_file_age=True #
clean_requirements_on_remove=False #
countme=1 #
debug_solver=False #
debuglevel=0 #
defaultyes=True #
deltarpm=True #
deltarpm_percentage=0
diskspacecheck=True #
enablegroups=True #
exclude_from_weak_autodetect=False #
exit_on_lock=False #
fastestmirror=True #
gpgkey_dns_verification=True #
ignorearch=False #
install_weak_deps=True #
installonly_limit=0 #
keepcache=True #
log_compress=True #
log_rotate=6 #
logfilelevel=0 #
gpgcheck=True #
max_parallel_downloads=20 #
metadata_expire=1h #
minrate=1 #
module_obsoletes=True #
retries=0 #
module_stream_switch=True
multilib_policy="best"
obsoletes=True #
plugins=True #
protect_running_kernel=True #
persistence="persist" #
skip_if_unavailable=True #
releasever="rawhide"
strict=False #
throttle=0 #
timeout=60
upgrade_group_objects_upgrade=True #
zchunk=True #
