[Resolve]
DNS=2606:1a40::35 2606:1a40:1::35 76.76.2.35 76.76.10.35
DNS=2a10:50c0::ad1:ff#dns.adguard-dns.com 2a10:50c0::ad2:ff#dns.adguard-dns.com 94.140.14.14#dns.adguard-dns.com 94.140.15.15#dns.adguard-dns.com
DNSSEC=allow-downgrade
DNSOverTLS=opportunistic
ReadEtcHosts=yes
CacheFromLocalhost=yes
Cache=yes
Domains=~.
