[Time]
NTP=time.google.com time.windows.com time.cloudflare.com pool.ntp.org time.facebook.com time.apple.com time.aws.com
RootDistanceMaxSec=120
PollIntervalMinSec=17
PollIntervalMaxSec=65535
ConnectionRetrySec=2
