[Unit]
Description=Contributes idle computing time
Wants=vboxdrv.service
After=vboxdrv.service network-online.target

[Service]
Type=simple
ProtectHome=true
ProtectSystem=full
ProtectControlGroups=true
ReadWritePaths=-/var/lib/boinc -/etc/boinc-client
Nice=19
User=boinc
WorkingDirectory=/var/lib/boinc
ExecStart=/usr/bin/boinc
ExecStopPost=/bin/rm -f lockfile
Restart=always
RestartSec=1s
IOSchedulingPriority=7
IOSchedulingClass=best-effort
RestrictRealtime=true

[Install]
WantedBy=multi-user.target
